@BASE_URL = http://localhost:5193

@BOOKING_ID = BOOKING_ID
@RESOURCE_ID = RESOURCE_ID
@START_TIME = 2026-09-07T12:00:00Z
@END_TIME = 2026-09-07T13:00:00Z

### BOOKINGS - Get all bookings
GET {{BASE_URL}}/api/Bookings
Accept: application/json

### BOOKING - Get booking
GET {{BASE_URL}}/api/Bookings/{{BOOKING_ID}}
Accept: application/json

### CREATE - Create booking
POST {{BASE_URL}}/api/Bookings/
Content-Type: application/json

{
  "resourceId": "{{RESOURCE_ID}}",
  "startTime": "{{START_TIME}}",
  "endTime": "{{END_TIME}}"
}

### UPDATE - Update booking
PUT {{BASE_URL}}/api/Bookings/{{BOOKING_ID}}
Content-Type: application/json

{
  "resourceId": "{{RESOURCE_ID}}",
  "startTime": "{{START_TIME}}",
  "endTime": "{{END_TIME}}"
}

### CANCEL - Cancel booking
PATCH {{BASE_URL}}/api/Bookings/{{BOOKING_ID}}/cancel
Content-Type: application/json
