@BASE_URL = http://localhost:5193

@RESOURCE_ID = RESOURCE_ID
@NAME = Skrivbord
@RESOURCE_TYPE_ID = RESOURCE_TYPE_ID
@CAPACITY = 5
@IS_ACTIVE = true


### RESOURCES - Get all resources
GET {{BASE_URL}}/api/Resource
Accept: application/json

### RESOURCE - Get resource by ID
GET {{BASE_URL}}/api/Resource/{{RESOURCE_ID}}
Accept: application/json

### CREATE - Create resource
POST {{BASE_URL}}/api/Resource
Content-Type: application/json

{
  "name": "{{NAME}}",
  "resourceTypeId": "{{RESOURCE_TYPE_ID}}",
  "capacity": {{CAPACITY}}
}

### UPDATE - Update resource
PUT {{BASE_URL}}/api/Resource/{{RESOURCE_ID}}
Content-Type: application/json

{
  "name": "{{NAME}}",
  "resourceTypeId": "{{RESOURCE_TYPE_ID}}",
  "capacity": {{CAPACITY}},
  "isActive": {{IS_ACTIVE}}
}

### DELETE - Delete resource
DELETE {{BASE_URL}}/api/Resource/{{RESOURCE_ID}}